steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east1-docker.pkg.dev/annular-heading-423723-a4/tienda/payment-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/annular-heading-423723-a4/tienda/payment-ms',
      ]
